### ISSUE TITLE
Restore Purchases Returns Empty Entitlements for Valid Google Play Purchases

### ISSUE THREAD

**Issue by wesjon** [qonversion/android-sdk#733]
## Issue Summary
The `Qonversion.shared.restore()` method is returning empty entitlements for users who have valid, active purchases through Google Play. This issue started on **October 28, 2025** and has affected approximately **30 users** who have contacted support (probably more). On this date I migrated to the new One-Time products from Google Play which are supposed to be supported and be backwards compatible.

![Image](https://github.com/user-attachments/assets/b1a2b6f1-6ed0-40be-bbe7-ea5be96183b1)

## Impact
- **Severity**: Critical - Paying customers cannot access premium features they purchased
- **Affected Users**: ~30 users (and growing) who purchased through Google Play
- **Scenarios**:
  - Users who clear app data and try to restore purchases
  - Users who install the app on a new device with the same Google account
- **Purchase Flow**: Initial purchases work correctly, but restoration fails (success in the callback restore but empty entitlements)

## Environment
- **Qonversion SDK Version**: 8.2.6 and 9.0.2
- **Platform**: Android
- **Min SDK**: 24
- **Target SDK**: 36
- **Compile SDK**: 36
- **Kotlin**: 2.2.21
- **Build Environment**: Production (tested and confirmed)
- **Launch Mode**: `QLaunchMode.SubscriptionManagement`

## SDK Initialization

```kotlin
private fun setupBilling() {
    Qonversion.initialize(
        QonversionConfig.Builder(
            this,
            "<MY KEY>",
            QLaunchMode.SubscriptionManagement,
        )
            .setEnvironment(if (BuildConfig.DEBUG) QEnvironment.Sandbox else QEnvironment.Production)
            .setFallbackFileIdentifier(R.raw.qonversion_android_fallbacks)
            .build(),
    )

    tryOrLog {
        Qonversion.shared.syncPurchases()
        Qonversion.shared.products(object : QonversionProductsCallback {
            override fun onError(error: QonversionError) {
                Timber.e("Qonversion error: ${error.description}")
            }

            override fun onSuccess(products: Map<String, QProduct>) {
                Timber.d("Products fetched successfully. Count: ${products.size}")
            }
        })
    }

    FirebaseAnalytics.getInstance(this).appInstanceId.addOnCompleteListener { task ->
        task.result?.let { appInstanceId ->
            Qonversion.shared.setUserProperty(
                QUserPropertyKey.FirebaseAppInstanceId,
                appInstanceId,
            )
        }
    }
}
```

## Restore Purchase Implementation

```kotlin
// Extension function wrapper
suspend fun Qonversion.restorePurchases(): QEntitlement? =
        suspendCoroutine { continuation ->
                this.restore(
                    object : QonversionEntitlementsCallback {
                        override fun onError(error: QonversionError) {
                            continuation.resume(null)
                        }

                        override fun onSuccess(entitlements: Map<String, QEntitlement>) {
                            // Here I validate if entitlement are active, but it's not returning anything in the map
                            continuation.resume(entitlements.values.find {
                                it.hasPremiumEntitlement(validateActive = true)
                            })
                        }
                    },
                )
        }

// Repository method
override suspend fun restorePurchases(): Boolean {
    try {
        val hasRestoredPurchases =
            Qonversion.shared.restorePurchases().hasPremiumEntitlement()
    } catch (ex: Throwable) {
        Timber.e(ex)
        return false
    }
}

// Entitlement validation
fun QEntitlement?.hasPremiumEntitlement(validateActive: Boolean = true): Boolean {
    val isPremiumEntitlement = this?.id in premiumEntitlements
    val isValid = if (validateActive) {
        this?.isActive == true
    } else {
        true
    }
    return isPremiumEntitlement && isValid
}
```

## Expected Behavior
When a user with a valid Google Play purchase calls `restore()`:
1. The SDK should communicate with Google Play Billing
2. Retrieve the user's active subscriptions/purchases
3. Return a non-empty entitlements map containing the user's premium entitlement
4. The app should successfully restore premium access

## Actual Behavior
When `restore()` is called:
1. The `onSuccess` callback is triggered (not `onError`)
2. The entitlements map is **completely empty** (`{}`)
3. Production logs confirm: `restorePurchases#onSuccess: {}`
4. Users cannot access premium features they legitimately purchased
5. This happens consistently for affected users across app reinstalls and device changes

## Steps to Reproduce
1. Purchase a premium subscription/product through Google Play (this works)
2. Either:
   - Clear the app data in Android settings
   - OR install the app on a new device using the same Google account
3. Open the app and tap "Restore Purchases"
4. Observe: Restore returns empty entitlements despite valid Google Play purchase

## Timeline
- **Before October 28, 2025**: Restore purchases worked correctly
- **October 28, 2025**: Issue started - restore began returning empty entitlements, **One Time Product Migrated on Google Play**
- **October 31, 2025**: Temporarily upgraded to SDK 9.0.2 to attempt fix
- **November 2, 2025**: Reverted to 8.2.6 as 9.0.2 had API breaking changes
- No code changes to our restore logic during this period

## Additional Context
- The **initial purchase flow works perfectly** - users can successfully purchase and receive entitlements
- Only the **restore** functionality is broken
- Issue is consistent and reproducible in production environment
- The `restore()` callback does not error - it succeeds but returns empty data
- We have implemented comprehensive logging which confirms empty entitlements map
- We also call `syncPurchases()` during initialization, but this doesn't resolve the restore issue

Can you help me with this issue? Is there something else I should be doing in order to be able to restore user's purchases?

**Comment by dmitdu** [comment]
Same here, getting dozens of mails on support channel about premium users unable to restore their subscriptions. That is really sad

**Comment by michaldrabik** [comment]
I can join the others that commented above. Started getting some support emails that they are unable to restore a valid in app purchases from 2024 after switching the phone. Already verified with them that indeed the same Google account is being used.

Some insights would be helpful :)

**Comment by NickSxti** [comment]
Hello!
The development took some extra time, as it was a part of a major release to support the new Google API.
We plan to deliver the fix during January.
I'll get back with a set ETA as soon as I get the date.

**Comment by NickSxti** [comment]
Hello!
The issue was fixed!
If the case recurs, please reopen the issue.

**Comment by NickSxti** [comment]
Hello @dmitdu!
The issue was resolved by backend changes, which do not require SDK updates.
If the issue reappears, please provide more details in a Support ticket (Qon_uids or transaction_ids)

**Comment by wesjon** [comment]
Hi @NickSxti, we ran tests and while we did notice a reduction of about 20% in restore purchase tickets, unfortunately, the issue is still happening.

We get about 10 tickets regarding this issue, and we got 8 today.

IDs belonging to the same Google account for reference:
QON_7d37f6e38397466dba4a4910431dd798 
QON_8fda0eaac8134a88a880a1b78c135a62

**Comment by NickSxti** [comment]
Hey @wesjon !
Thank you for the details!
I'll run an investigation on our side and sync with our dev team.
I will keep you updated.

**Comment by dmitdu** [comment]
Messages from frustrated users continue to accumulate.

**Comment by SpertsyanKM** [comment]
Unfortunately, these cases should be fixed manually, because if the purchase was made on the previous Qonversion SDK version (even before the last major), the non-consumable in-app would have been consumed, causing it to disappear in the Google Play history result requested on restore, so we are unable to restore the entitlement. 

The fix will resolve this issue for all future purchases made from SDK 9.2.2

**Comment by NickSxti** [comment]
Hello!
The issue was fixed.
Could you check please?
